# Generated by Django 4.2 on 2024-08-28 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artistas',
            new_name='Artista',
        ),
    ]
