# Generated by Django 4.2 on 2024-08-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0002_rename_artistas_artista'),
    ]

    operations = [
        migrations.AddField(
            model_name='artista',
            name='orden',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='album',
            table='mi_aplicacion_album',
        ),
        migrations.AlterModelTable(
            name='artista',
            table='mi_aplicacion_artistas',
        ),
        migrations.AlterModelTable(
            name='cancion',
            table='mi_aplicacion_cancion',
        ),
    ]
