# Generated by Django 4.2 on 2024-08-31 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0004_alter_artista_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='orden',
            field=models.IntegerField(),
        ),
    ]
